# Generated by Django 5.2.17 on 2026-09-21 01:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_teaching_structure'),
        ('resources', '0002_rooms_and_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='working_days', to='academics.semester')),
            ],
            options={
                'verbose_name': 'working day',
                'verbose_name_plural': 'working days',
                'ordering': ('semester', 'day_of_week'),
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('working_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='scheduling.workingday')),
            ],
            options={
                'verbose_name': 'time slot',
                'verbose_name_plural': 'time slots',
                'ordering': ('working_day', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='BreakPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('working_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_periods', to='scheduling.workingday')),
            ],
            options={
                'verbose_name': 'break period',
                'verbose_name_plural': 'break periods',
                'ordering': ('working_day', 'start_time'),
            },
        ),
        migrations.CreateModel(
            name='CalendarException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exception_type', models.CharField(choices=[('HOLIDAY', 'Holiday'), ('EXAM', 'Examination'), ('EVENT', 'Event'), ('MAINTENANCE', 'Maintenance'), ('INSTRUCTOR_ABSENCE', 'Instructor absence'), ('ROOM_CLOSURE', 'Room closure')], max_length=32)),
                ('scope_type', models.CharField(choices=[('COLLEGE', 'College-wide'), ('DEPARTMENT', 'Department'), ('INSTRUCTOR', 'Instructor'), ('ROOM', 'Room'), ('STUDENT_GROUP', 'Student group')], max_length=32)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calendar_exceptions', to='academics.department')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calendar_exceptions', to='resources.instructorprofile')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calendar_exceptions', to='resources.room')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calendar_exceptions', to='academics.semester')),
                ('student_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calendar_exceptions', to='academics.studentgroup')),
            ],
            options={
                'verbose_name': 'calendar exception',
                'verbose_name_plural': 'calendar exceptions',
                'ordering': ('-date', 'semester'),
                'indexes': [models.Index(fields=['semester', 'date'], name='cal_exc_semester_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('start_time__isnull', True), ('end_time__isnull', True)), models.Q(('start_time__isnull', False), ('end_time__isnull', False)), _connector='OR'), name='calendar_exception_time_window_complete'), models.CheckConstraint(condition=models.Q(('start_time__isnull', True), ('end_time__isnull', True), ('start_time__lt', models.F('end_time')), _connector='OR'), name='calendar_exception_start_before_end')],
            },
        ),
        migrations.AddConstraint(
            model_name='workingday',
            constraint=models.UniqueConstraint(fields=('semester', 'day_of_week'), name='unique_working_day_per_semester'),
        ),
        migrations.AddConstraint(
            model_name='workingday',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='working_day_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('working_day', 'sequence'), name='unique_time_slot_sequence_per_working_day'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gte', 1)), name='time_slot_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='time_slot_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('working_day', 'start_time', 'end_time'), name='unique_active_time_slot_window'),
        ),
        migrations.AddConstraint(
            model_name='breakperiod',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='break_period_start_before_end'),
        ),
    ]
