# Generated by Django 5.2.17 on 2026-09-21 14:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_teaching_structure'),
        ('resources', '0002_rooms_and_requirements'),
        ('scheduling', '0001_calendar_and_time_configuration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('DEPARTMENT', 'Department'), ('COLLEGE', 'College')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='academics.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='academics.semester')),
            ],
            options={
                'verbose_name': 'schedule',
                'verbose_name_plural': 'schedules',
                'ordering': ('semester', 'scope', 'department'),
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=200)),
                ('candidate_id', models.CharField(max_length=300)),
                ('session_ordinal', models.PositiveIntegerField(help_text='1-based index of this session inside its teaching component.', validators=[django.core.validators.MinValueValidator(1)])),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('penalty', models.IntegerField(default=0)),
                ('course_id_snapshot', models.PositiveIntegerField()),
                ('course_code_snapshot', models.CharField(max_length=32)),
                ('course_name_snapshot', models.CharField(max_length=150)),
                ('offering_id_snapshot', models.PositiveIntegerField()),
                ('offering_code_snapshot', models.CharField(blank=True, default='', max_length=64)),
                ('component_type_snapshot', models.CharField(blank=True, default='', max_length=32)),
                ('component_label_snapshot', models.CharField(blank=True, default='', max_length=150)),
                ('managing_department_code_snapshot', models.CharField(max_length=32)),
                ('managing_department_name_snapshot', models.CharField(max_length=150)),
                ('room_code_snapshot', models.CharField(blank=True, default='', max_length=32)),
                ('room_name_snapshot', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('managing_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_entries', to='academics.department')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_entries', to='resources.room')),
                ('teaching_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_entries', to='academics.teachingcomponent')),
            ],
            options={
                'verbose_name': 'schedule entry',
                'verbose_name_plural': 'schedule entries',
                'ordering': ('schedule_version', 'day_of_week', 'start_time', 'session_id'),
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntryInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_role_snapshot', models.CharField(blank=True, default='', max_length=32)),
                ('full_name_snapshot', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_entry_instructors', to='resources.instructorprofile')),
                ('schedule_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='scheduling.scheduleentry')),
            ],
            options={
                'verbose_name': 'schedule entry instructor',
                'verbose_name_plural': 'schedule entry instructors',
                'ordering': ('schedule_entry', 'instructor'),
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntryStudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_snapshot', models.CharField(max_length=32)),
                ('name_snapshot', models.CharField(max_length=100)),
                ('department_id_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('department_code_snapshot', models.CharField(blank=True, default='', max_length=32)),
                ('department_name_snapshot', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='scheduling.scheduleentry')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_entry_groups', to='academics.studentgroup')),
            ],
            options={
                'verbose_name': 'schedule entry student group',
                'verbose_name_plural': 'schedule entry student groups',
                'ordering': ('schedule_entry', 'student_group'),
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntryTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='1-based position of this period inside the entry.', validators=[django.core.validators.MinValueValidator(1)])),
                ('sequence_snapshot', models.IntegerField()),
                ('label_snapshot', models.CharField(blank=True, default='', max_length=100)),
                ('start_time_snapshot', models.TimeField()),
                ('end_time_snapshot', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='scheduling.scheduleentry')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_entry_slots', to='scheduling.timeslot')),
            ],
            options={
                'verbose_name': 'schedule entry time slot',
                'verbose_name_plural': 'schedule entry time slots',
                'ordering': ('schedule_entry', 'position'),
            },
        ),
        migrations.CreateModel(
            name='ScheduleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(help_text='1 for the first persisted generation, then 2, 3, ...', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=32)),
                ('source', models.CharField(choices=[('DEPARTMENT_GENERATION', 'Department generation'), ('COLLEGE_GENERATION', 'College generation')], max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('solver_status', models.CharField(blank=True, default='', max_length=32)),
                ('objective_value', models.IntegerField(blank=True, null=True)),
                ('solver_wall_time_seconds', models.FloatField(blank=True, null=True)),
                ('solver_num_conflicts', models.IntegerField(blank=True, null=True)),
                ('solver_num_branches', models.IntegerField(blank=True, null=True)),
                ('validation_summary', models.JSONField(blank=True, default=dict)),
                ('generation_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_versions', to=settings.AUTH_USER_MODEL)),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_versions', to='scheduling.scheduleversion')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='scheduling.schedule')),
            ],
            options={
                'verbose_name': 'schedule version',
                'verbose_name_plural': 'schedule versions',
                'ordering': ('schedule', '-version_number'),
            },
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='schedule_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='scheduling.scheduleversion'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'DEPARTMENT')), fields=('semester', 'department'), name='sched_uniq_dept_scope'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'COLLEGE')), fields=('semester',), name='sched_uniq_college_scope'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('department__isnull', False), ('scope', 'DEPARTMENT')), models.Q(('department__isnull', True), ('scope', 'COLLEGE')), _connector='OR'), name='sched_scope_dept_consistency'),
        ),
        migrations.AddConstraint(
            model_name='scheduleentryinstructor',
            constraint=models.UniqueConstraint(fields=('schedule_entry', 'instructor'), name='schedinst_uniq_instructor'),
        ),
        migrations.AddConstraint(
            model_name='scheduleentrystudentgroup',
            constraint=models.UniqueConstraint(fields=('schedule_entry', 'student_group'), name='schedgroup_uniq_group'),
        ),
        migrations.AddConstraint(
            model_name='scheduleentrytimeslot',
            constraint=models.UniqueConstraint(fields=('schedule_entry', 'time_slot'), name='schedslot_uniq_slot'),
        ),
        migrations.AddConstraint(
            model_name='scheduleentrytimeslot',
            constraint=models.UniqueConstraint(fields=('schedule_entry', 'position'), name='schedslot_uniq_position'),
        ),
        migrations.AddConstraint(
            model_name='scheduleentrytimeslot',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='schedslot_position_min_one'),
        ),
        migrations.AddConstraint(
            model_name='scheduleentrytimeslot',
            constraint=models.CheckConstraint(condition=models.Q(('start_time_snapshot__lt', models.F('end_time_snapshot'))), name='schedslot_time_order'),
        ),
        migrations.AddConstraint(
            model_name='scheduleversion',
            constraint=models.UniqueConstraint(fields=('schedule', 'version_number'), name='schedver_uniq_number'),
        ),
        migrations.AddConstraint(
            model_name='scheduleversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gte', 1)), name='schedver_number_min_one'),
        ),
        migrations.AddIndex(
            model_name='scheduleentry',
            index=models.Index(fields=['schedule_version', 'day_of_week'], name='schedentry_version_day_idx'),
        ),
        migrations.AddConstraint(
            model_name='scheduleentry',
            constraint=models.UniqueConstraint(fields=('schedule_version', 'session_id'), name='schedentry_uniq_session'),
        ),
        migrations.AddConstraint(
            model_name='scheduleentry',
            constraint=models.UniqueConstraint(fields=('schedule_version', 'teaching_component', 'session_ordinal'), name='schedentry_uniq_component'),
        ),
        migrations.AddConstraint(
            model_name='scheduleentry',
            constraint=models.CheckConstraint(condition=models.Q(('session_ordinal__gte', 1)), name='schedentry_ordinal_min_one'),
        ),
        migrations.AddConstraint(
            model_name='scheduleentry',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='schedentry_time_order'),
        ),
        migrations.AddConstraint(
            model_name='scheduleentry',
            constraint=models.CheckConstraint(condition=models.Q(('penalty__gte', 0)), name='schedentry_penalty_nonneg'),
        ),
    ]
