# Generated by Django 5.2.17 on 2026-09-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_schedule_persistence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleversion',
            name='solver_status',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleversion',
            name='source',
            field=models.CharField(choices=[('DEPARTMENT_GENERATION', 'Department generation'), ('COLLEGE_GENERATION', 'College generation'), ('MANUAL_EDIT', 'Manual edit')], max_length=40),
        ),
    ]
