# Generated by Django 5.2.17 on 2026-09-21 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_manual_edit_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='published_version',
            field=models.ForeignKey(blank=True, help_text='The currently authoritative published version of this schedule. Only a college schedule may point at one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_for_schedules', to='scheduling.scheduleversion'),
        ),
        migrations.AddField(
            model_name='scheduleversion',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleversion',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_schedule_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleversion',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleversion',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_schedule_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleversion',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleversion',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_schedule_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduleversion',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleversion',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_schedule_versions', to=settings.AUTH_USER_MODEL),
        ),
    ]
