# Generated by Django 5.2.17 on 2026-09-22 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_teaching_structure'),
        ('scheduling', '0004_workflow_publication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('DEPARTMENT_DRAFT_GENERATED', 'Department draft generated'), ('COLLEGE_DRAFT_GENERATED', 'College draft generated'), ('MANUAL_EDIT_APPLIED', 'Manual edit applied'), ('SCHEDULE_SUBMITTED', 'Schedule version submitted'), ('SCHEDULE_REVIEWED', 'Schedule version reviewed'), ('SCHEDULE_APPROVED', 'Schedule version approved'), ('SCHEDULE_PUBLISHED', 'Schedule version published'), ('SEMESTER_PLAN_IMPORTED', 'Semester teaching plan imported')], db_index=True, max_length=64)),
                ('actor_username_snapshot', models.CharField(blank=True, default='', max_length=150)),
                ('actor_role_snapshot', models.CharField(blank=True, default='', max_length=32)),
                ('object_type', models.CharField(blank=True, default='', max_length=64)),
                ('object_id', models.CharField(blank=True, default='', max_length=128)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, help_text='Who performed the operation; null after the account is removed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Owning department of the operation, when it has one. Null marks a college-wide operation, which only college administrators may read.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='academics.department')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='scheduling.schedule')),
                ('schedule_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='scheduling.scheduleversion')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='academics.semester')),
            ],
            options={
                'verbose_name': 'audit event',
                'verbose_name_plural': 'audit events',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['department', 'created_at'], name='scheduling__departm_5b84e0_idx'), models.Index(fields=['semester', 'created_at'], name='scheduling__semeste_daea34_idx'), models.Index(fields=['schedule', 'created_at'], name='scheduling__schedul_bb560f_idx'), models.Index(fields=['actor', 'created_at'], name='scheduling__actor_i_ba73ad_idx')],
            },
        ),
    ]
