# Generated by Django 5.2.17 on 2026-09-20 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Owning department; a college administrator may have none.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='academics.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('COLLEGE_ADMIN', 'College Administrator'), ('DEPARTMENT_ADMIN', 'Department Administrator'), ('SCHEDULER', 'Scheduler'), ('VIEWER', 'Viewer'), ('INSTRUCTOR', 'Instructor')], default='VIEWER', help_text="Application role; least privilege ('Viewer') by default.", max_length=32),
        ),
    ]
