# Generated by Django 5.2.17 on 2026-09-20 15:50

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(help_text='Short college identifier, for example AI, ENG or MED.', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'college',
                'verbose_name_plural': 'colleges',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'academic year',
                'verbose_name_plural': 'academic years',
                'ordering': ('-start_year',),
                'constraints': [models.UniqueConstraint(fields=('start_year', 'end_year'), name='unique_academic_year_range'), models.CheckConstraint(condition=models.Q(('end_year', django.db.models.expressions.CombinedExpression(models.F('start_year'), '+', models.Value(1)))), name='academic_year_years_are_consecutive')],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='college',
            field=models.ForeignKey(blank=True, help_text='Owning college. Nullable so department rows created before Phase 2 stay valid.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='academics.college'),
        ),
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20)),
                ('study_type', models.CharField(choices=[('UNDERGRADUATE', 'Undergraduate'), ('MASTER', 'Master'), ('PHD', 'PhD')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='academics.department')),
            ],
            options={
                'verbose_name': 'study program',
                'verbose_name_plural': 'study programs',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StudyStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='academics.studyprogram')),
            ],
            options={
                'verbose_name': 'study stage',
                'verbose_name_plural': 'study stages',
                'ordering': ('program__name', 'number'),
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_group', models.ForeignKey(blank=True, help_text='Parent group when this group is a practical-class subgroup.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subgroups', to='academics.studentgroup')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='academics.studystage')),
            ],
            options={
                'verbose_name': 'student group',
                'verbose_name_plural': 'student groups',
                'ordering': ('stage', 'code'),
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(choices=[(1, 'First'), (2, 'Second')])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semesters', to='academics.academicyear')),
            ],
            options={
                'verbose_name': 'semester',
                'verbose_name_plural': 'semesters',
                'ordering': ('-academic_year__start_year', 'number'),
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'number'), name='unique_semester_number_per_academic_year'), models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='semester_end_date_not_before_start_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='studyprogram',
            constraint=models.UniqueConstraint(fields=('department', 'code'), name='unique_program_code_per_department'),
        ),
        migrations.AddConstraint(
            model_name='studystage',
            constraint=models.UniqueConstraint(fields=('program', 'number'), name='unique_stage_number_per_program'),
        ),
        migrations.AddConstraint(
            model_name='studystage',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1)), name='study_stage_number_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='studentgroup',
            constraint=models.UniqueConstraint(fields=('stage', 'code'), name='unique_group_code_per_stage'),
        ),
        migrations.AddConstraint(
            model_name='studentgroup',
            constraint=models.CheckConstraint(condition=models.Q(('pk', models.F('parent_group')), _negated=True), name='student_group_parent_group_not_self'),
        ),
    ]
