# Generated by Django 5.2.17 on 2026-09-20 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academic_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(help_text='Course code, for example ML301 or BIO102.', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(help_text='Department that owns the course academically.', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.department')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offering_code', models.CharField(default='MAIN', help_text='Short instance label, for example MAIN, A or EVENING.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='academics.course')),
                ('managing_department', models.ForeignKey(help_text='Department responsible for delivering the offering.', on_delete=django.db.models.deletion.PROTECT, related_name='managed_course_offerings', to='academics.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_offerings', to='academics.semester')),
            ],
            options={
                'verbose_name': 'course offering',
                'verbose_name_plural': 'course offerings',
                'ordering': ('course__code', 'offering_code'),
            },
        ),
        migrations.CreateModel(
            name='TeachingComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('THEORY', 'Theory'), ('PRACTICAL', 'Practical')], max_length=20)),
                ('label', models.CharField(blank=True, default='', help_text='Human-readable label; not semantically authoritative.', max_length=100)),
                ('weekly_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('session_duration_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='academics.courseoffering')),
            ],
            options={
                'verbose_name': 'teaching component',
                'verbose_name_plural': 'teaching components',
                'ordering': ('offering', 'component_type', 'label'),
            },
        ),
        migrations.CreateModel(
            name='TeachingComponentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='component_links', to='academics.studentgroup')),
                ('teaching_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_links', to='academics.teachingcomponent')),
            ],
            options={
                'verbose_name': 'teaching component group',
                'verbose_name_plural': 'teaching component groups',
                'ordering': ('teaching_component', 'student_group'),
            },
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('department', 'code'), name='unique_course_code_per_department'),
        ),
        migrations.AddConstraint(
            model_name='courseoffering',
            constraint=models.UniqueConstraint(fields=('course', 'semester', 'offering_code'), name='unique_offering_code_per_course_semester'),
        ),
        migrations.AddConstraint(
            model_name='teachingcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('weekly_hours__gt', 0)), name='teaching_component_weekly_hours_positive'),
        ),
        migrations.AddConstraint(
            model_name='teachingcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('session_duration_hours__gt', 0)), name='teaching_component_session_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='teachingcomponentgroup',
            constraint=models.UniqueConstraint(fields=('teaching_component', 'student_group'), name='unique_group_per_teaching_component'),
        ),
    ]
