# Generated by Django 5.2.17 on 2026-09-20 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_teaching_structure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_code', models.CharField(blank=True, help_text='Optional institutional identifier; blank values are stored as NULL.', max_length=32, null=True, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('academic_title', models.CharField(blank=True, default='', help_text='Free text, for example Professor or Assistant Lecturer.', max_length=100)),
                ('max_weekly_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_daily_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sharing_scope', models.CharField(choices=[('PRIVATE', 'Private (primary department only)'), ('SELECTED_DEPARTMENTS', 'Selected departments'), ('COLLEGE_WIDE', 'College-wide')], default='PRIVATE', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_department', models.ForeignKey(help_text='Department that owns this instructor resource.', on_delete=django.db.models.deletion.PROTECT, related_name='instructors', to='academics.department')),
                ('user', models.OneToOneField(blank=True, help_text='Optional login account; a profile may exist before an account is created.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'instructor profile',
                'verbose_name_plural': 'instructor profiles',
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='InstructorPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('preference_type', models.CharField(choices=[('PREFERRED', 'Preferred'), ('AVOID', 'Avoid')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructor_preferences', to='academics.semester')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='resources.instructorprofile')),
            ],
            options={
                'verbose_name': 'instructor preference',
                'verbose_name_plural': 'instructor preferences',
                'ordering': ('instructor', 'day_of_week', 'start_time'),
            },
        ),
        migrations.CreateModel(
            name='InstructorDepartmentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_access_grants', to='academics.department')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_access', to='resources.instructorprofile')),
            ],
            options={
                'verbose_name': 'instructor department access',
                'verbose_name_plural': 'instructor department access grants',
                'ordering': ('instructor', 'department'),
            },
        ),
        migrations.CreateModel(
            name='InstructorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructor_availability', to='academics.semester')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='resources.instructorprofile')),
            ],
            options={
                'verbose_name': 'instructor availability',
                'verbose_name_plural': 'instructor availability windows',
                'ordering': ('instructor', 'day_of_week', 'start_time'),
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_role', models.CharField(choices=[('PRIMARY', 'Primary'), ('ASSISTANT', 'Assistant')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='resources.instructorprofile')),
                ('teaching_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructor_assignments', to='academics.teachingcomponent')),
            ],
            options={
                'verbose_name': 'teaching assignment',
                'verbose_name_plural': 'teaching assignments',
                'ordering': ('teaching_component', 'assignment_role', 'instructor'),
            },
        ),
        migrations.AddConstraint(
            model_name='instructorprofile',
            constraint=models.CheckConstraint(condition=models.Q(('max_weekly_hours__isnull', True), ('max_weekly_hours__gt', 0), _connector='OR'), name='instructor_max_weekly_hours_positive'),
        ),
        migrations.AddConstraint(
            model_name='instructorprofile',
            constraint=models.CheckConstraint(condition=models.Q(('max_daily_hours__isnull', True), ('max_daily_hours__gt', 0), _connector='OR'), name='instructor_max_daily_hours_positive'),
        ),
        migrations.AddConstraint(
            model_name='instructorprofile',
            constraint=models.CheckConstraint(condition=models.Q(('max_weekly_hours__isnull', True), ('max_daily_hours__isnull', True), ('max_daily_hours__lte', models.F('max_weekly_hours')), _connector='OR'), name='instructor_daily_hours_not_above_weekly'),
        ),
        migrations.AddConstraint(
            model_name='instructorpreference',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='instructor_preference_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='instructorpreference',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('instructor', 'semester', 'day_of_week', 'start_time', 'end_time'), name='unique_active_instructor_preference_window'),
        ),
        migrations.AddConstraint(
            model_name='instructordepartmentaccess',
            constraint=models.UniqueConstraint(fields=('instructor', 'department'), name='unique_instructor_department_access'),
        ),
        migrations.AddConstraint(
            model_name='instructoravailability',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='instructor_availability_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='instructoravailability',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('instructor', 'semester', 'day_of_week', 'start_time', 'end_time'), name='unique_active_instructor_availability_window'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(fields=('teaching_component', 'instructor'), name='unique_instructor_per_teaching_component'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('assignment_role', 'PRIMARY'), ('is_active', True)), fields=('teaching_component',), name='single_active_primary_instructor_per_component'),
        ),
    ]
