# Generated by Django 5.2.17 on 2026-09-20 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_teaching_structure'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Short code, for example COMPUTERS or PROJECTOR.', max_length=32, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'room capability',
                'verbose_name_plural': 'room capabilities',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Short code, for example LECTURE_HALL or COMPUTER_LAB.', max_length=32, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'room type',
                'verbose_name_plural': 'room types',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(help_text='Globally unique physical room code, for example AI-LAB-1.', max_length=32, unique=True)),
                ('capacity', models.PositiveIntegerField(help_text='Number of students the room can host.')),
                ('sharing_scope', models.CharField(choices=[('PRIVATE', 'Private (primary department only)'), ('SELECTED_DEPARTMENTS', 'Selected departments'), ('COLLEGE_WIDE', 'College-wide')], default='PRIVATE', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_department', models.ForeignKey(help_text='Department that owns this room.', on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='academics.department')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='resources.roomtype')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='TeachingComponentRoomRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_capacity', models.PositiveIntegerField(blank=True, help_text='Explicit minimum capacity override; null means the expected student count decides.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_room_type', models.ForeignKey(blank=True, help_text='Null means no specific room-type restriction.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room_requirements', to='resources.roomtype')),
                ('teaching_component', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='room_requirement', to='academics.teachingcomponent')),
            ],
            options={
                'verbose_name': 'teaching component room requirement',
                'verbose_name_plural': 'teaching component room requirements',
                'ordering': ('teaching_component',),
            },
        ),
        migrations.CreateModel(
            name='TeachingComponentCapabilityRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_requirements', to='resources.roomcapability')),
                ('room_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_requirements', to='resources.teachingcomponentroomrequirement')),
            ],
            options={
                'verbose_name': 'teaching component capability requirement',
                'verbose_name_plural': 'teaching component capability requirements',
                'ordering': ('room_requirement', 'capability'),
            },
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='resources.room')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_availability', to='academics.semester')),
            ],
            options={
                'verbose_name': 'room availability',
                'verbose_name_plural': 'room availability windows',
                'ordering': ('room', 'day_of_week', 'start_time'),
                'constraints': [models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='room_availability_start_before_end'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('room', 'semester', 'day_of_week', 'start_time', 'end_time'), name='unique_active_room_availability_window')],
            },
        ),
        migrations.CreateModel(
            name='RoomCapabilityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to='resources.roomcapability')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_assignments', to='resources.room')),
            ],
            options={
                'verbose_name': 'room capability assignment',
                'verbose_name_plural': 'room capability assignments',
                'ordering': ('room', 'capability'),
                'constraints': [models.UniqueConstraint(fields=('room', 'capability'), name='unique_capability_per_room')],
            },
        ),
        migrations.CreateModel(
            name='RoomDepartmentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_access_grants', to='academics.department')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_access', to='resources.room')),
            ],
            options={
                'verbose_name': 'room department access',
                'verbose_name_plural': 'room department access grants',
                'ordering': ('room', 'department'),
                'constraints': [models.UniqueConstraint(fields=('room', 'department'), name='unique_room_department_access')],
            },
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='room_capacity_at_least_one'),
        ),
        migrations.AddConstraint(
            model_name='teachingcomponentroomrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_capacity__isnull', True), ('minimum_capacity__gte', 1), _connector='OR'), name='room_requirement_minimum_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='teachingcomponentcapabilityrequirement',
            constraint=models.UniqueConstraint(fields=('room_requirement', 'capability'), name='unique_capability_per_room_requirement'),
        ),
    ]
